### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/x-js". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by mediafish** [d4l-data4life/covapp#60]
Tried to install the App on my server and the page does not load. We get the error: 
_Failed to load module script: The server responded with a non-JavaScript MIME type of "text/x-js". Strict MIME type checking is enforced for module scripts per HTML spec._

Any idea how to solve that?

**Comment by radibit** [comment]
Hey @mediafish 👋 

I believe the problem you've experienced is due to a missing or wrong MIME type configured on the server where you're trying to install the app.

Could you please look for any `text/x-js` or `text/javascript js` MIME types in your server configuration and replace them with `application/javascript`.

In addition, there are several other comments in the following [thread](https://github.com/ionic-team/capacitor/issues/1878) that can also help you to investigate further the issue.

**Comment by radibit** [comment]
I'm closing this issue due to lack of further updates.
