### ISSUE TITLE
Improve FHIR code for NUM project 

### ISSUE THREAD

**Issue by fkaercher** [d4l-data4life/covapp#63]
related fkaercher/covapp#1

**Comment by me-d4l** [comment]
Hi @fkaercher - the Questionnaire FHIR resource which defines the CovApp questions is available from [our publicly available FHIR Implementation Guide](https://simplifier.net/guide/Covid-19Pre-TestPatientAssessment/Home). Specifically, the English and German versions are linked from [this page](https://simplifier.net/guide/Covid-19Pre-TestPatientAssessment/Questionnaire). The Questionnaire resource cannot be generated from a specific answer set (e.g. a QuestionnaireResponse resource) since the latter does not contain information about what all the allowed answers to a given question are, whether certain questions are only displayed under certain circumstances, various bits of meta-information etc.

**Comment by radibit** [comment]
I'm closing this issue due to lack of further updates.
